name: Metrics

on:
  schedule:
    - cron: "2 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'NaiHeBot' }}
    steps:
      - uses: lowlighter/metrics@master
        with:
          # GH Token
          token: ${{ secrets.GH_TOKEN }}
          
          # Options
          user: naiheeeee
          template: classic
          config_gemoji: yes
          config_timezone: Asia/Shanghai
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes

          # Committer
          committer_token: ${{ secrets.NAIHEBOT_GITHUB_TOKEN }}
          committer_message: ':memo: Update Profile (Metrics)'
          
          # base
          base: header, activity, community, repositories, metadata
          repositories_forks: yes
          repositories_affiliations: owner
          repositories_skipped: naiheeeee/naiheeeee
          
          # Language plugin
          plugin_languages: yes
          plugin_languages_skipped: unlock-music
          plugin_languages_ignored: 'inno setup'
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          
          # Followup plugin
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          # Traffic plugin
          plugin_traffic: yes

          # Isometric commit calendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Steam plugin
          plugin_steam_token: ${{ secrets.STEAM_API_KEY }}
          plugin_steam: yes
          plugin_steam_user: ${{ secrets.STEAM_ID }}

          # Anilist plugin
          plugin_anilist: yes
          plugin_anilist_user: NaiHe
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 1

          # Commit calendar plugin
          plugin_calendar: yes
          plugin_calendar_limit: 0