name: Update Steam Playtime

on:
  schedule:
    - cron: "2 0/2 * * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    name: Update-steam-playtime
    if: ${{ github.actor != 'NaiHeBot' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md,template/README-eta.md

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.NAIHEBOT_GITHUB_TOKEN }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - uses: actions/setup-go@v2
      - name: Clone and run steam-box
        run: |-
          git clone https://github.com/naiheeeee/steam-box.git
          cd steam-box && go build -o steam ./cmd/box/main.go
          mv ./steam ../ && cd .. && rm -rf steam-box/
      - name: Commit and push
        run: |-
          ./steam
          git config --global user.email "naiheeee6@gmail.com" && git config --global user.name "NaiHeBot"
          git diff
          git add README.md template/README-eta.md && git commit -m ":memo: Update Profile (Steam)" || exit 0
          git pull --rebase && git push