name: Update steam playtime

on:
  schedule:
    - cron: "2 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update-steam-playtime
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'NaiHeBot' }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.NAIHEBOT_GITHUB_TOKEN }}

      - name: Import GPG key for signing
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.NAIHEBOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Validate Go
        uses: actions/setup-go@v2

      - name: Clone and build steam-box
        run: |
          git clone https://github.com/naiheeeee/steam-box.git
          cd steam-box && go build -o steam ./cmd/box/main.go
          mv ./steam ../ && cd .. && rm -rf steam-box/

      - name: Run steam-box
        shell: sh
        run: |
          ./steam

      - name: Commit changes
        shell: bash
        env:
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GPG_TTY: /dev/null
        run: |
          set -eu
          
          mkdir -p ~/.gnupg
          echo 'no-tty' >> ~/.gnupg/gpg.conf
          echo 'batch' >> ~/.gnupg/gpg.conf
          echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf
          chmod 600 ~/.gnupg/gpg.conf
          
          git add README.md
          
          if ! git diff --cached --quiet; then
              git commit -S -m "Update Profile(Steam)"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.NAIHEBOT_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
