name: Update GitHub Profile Summary Cards

on:
  schedule: # execute every 24 hours
    - cron: "2 0 * * *"
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.actor != 'NaiHeBot' }}
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.NAIHEBOT_GITHUB_TOKEN }}
      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAME is optional, default to main, branch name to push cards
          BRANCH_NAME: "profile-summary-card-output"
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 8
          # EXCLUDE is an optional comma seperated list of languages to exclude, defaults to ""
          EXCLUDE: ""
          # AUTO_PUSH is optional, a boolean variable default to true, whether automatically push generated files to desired branch
          AUTO_PUSH: false

      - name: Commit and push
        run: |-
          git config --global user.email "naiheeee6@gmail.com" && git config --global user.name "NaiHeBot"
          git diff
          git add profile-summary-card-output && git commit -m ":memo: Update Profile (Summary Cards)" || exit 0
          git pull --rebase && git push